apiVersion: v1
kind: Service
metadata:
  name: digitrans-api-service
spec:
  type: LoadBalancer # Déploie automatiquement un répartiteur de charge élastique sur AWS
  selector:
    app: digitrans-api
  ports:
    - protocol: TCP
      port: 80         # Port public externe de l'application
      targetPort: 3000 # Redirection vers le port d'écoute interne de ton Node.js
